learning_templates/App/urls.py
from django.urls import path, re_path
from App import views

#Template tagging
app_name = 'App'

urlpatterns = [
    re_path(r'^relative/$',views.relative,name = 'relative'),
    re_path(r'^other/$',views.other,name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from App import views


urlpatterns = [
    re_path(r'^$',views.index, name = 'index'),
    path('admin/', admin.site.urls),
    re_path(r'^App/',include('App.urls'))

]

learning_templates/App/models.py
from django.db import models

# Create your models here.

learning_templates/App/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {'text': 'Hello_World','number':100}
    return render(request,'App/index.html', context_dict)

def other(request):
    return render(request,'App/other.html')

def relative(request):
    return render(request,'App/Relative_url_templates.html')

learning_templates/templates/App/Relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Page Title</title>
</head>
<body>

<h1>Welcome to Relative Url templates</h1>
<a href="{% url 'App:other' %}">The Other Page</a>
<a href="{% url 'admin:index' %}">Admin Page</a>
<a href="{% url 'index' %}">Home Page</a>

</body>
</html>

learning_templates/templates/App/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'App:other' %}">Other</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/App/index.html
<!DOCTYPE html>
{% extends "App/base.html"%}
   {% block body_block %}

      <h1> Welcome to Index page</h1>
      <h1>{{ text|cut:'hello' }}</h1>
      <h1>{{ number|add:"99" }}</h1>

    {% endblock  %}

learning_templates/templates/App/other.html
<!DOCTYPE html>
{% extends "App/base.html" %}
   {% block body_block %}

      <h1> Welcome to other page</h1>

    {% endblock  %}